ALTER SEQUENCE MP_CHARACTERISTIC_CH_ID_SEQ RESTART;
ALTER SEQUENCE MP_CONFIGURATION_CO_ID_SEQ RESTART;
ALTER SEQUENCE MP_DIRECTION_DI_ID_SEQ RESTART;
ALTER SEQUENCE MP_DIS_USE_DIUS_ID_SEQ RESTART;
ALTER SEQUENCE MP_LANGUAGE_LA_ID_SEQ RESTART;
ALTER SEQUENCE MP_OFFICE_OF_ID_SEQ RESTART;
ALTER SEQUENCE MP_OPTION_OP_ID_SEQ RESTART;
ALTER SEQUENCE MP_PAC_CHA_PACH_ID_SEQ RESTART;
ALTER SEQUENCE MP_RECEIVER_RE_ID_SEQ RESTART;
ALTER SEQUENCE MP_SHI_OPT_SHOP_ID_SEQ RESTART;
ALTER SEQUENCE MP_SHIPMENT_SH_ID_SEQ RESTART;
ALTER SEQUENCE MP_STATUS_ST_ID_SEQ RESTART;
ALTER SEQUENCE MP_STOP_ST_ID_SEQ RESTART;
ALTER SEQUENCE MP_USER_US_ID_SEQ RESTART;
ALTER SEQUENCE MP_DISCOUNT_DI_ID_SEQ RESTART;
ALTER SEQUENCE MP_PACKAGE_PA_ID_SEQ RESTART;

